In [1]:
import pandas as pd

df = pd.read_csv("../data/intrusion.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/intrusion.csv'

In [2]:
import os

print(os.listdir("../data"))

['02-14-2018.csv', '02-15-2018.csv', '02-16-2018.csv', '02-21-2018.csv', '02-22-2018.csv', '02-23-2018.csv', '02-28-2018.csv', '03-01-2018.csv', '03-02-2018.csv']

In [3]:
import os

for file in os.listdir("../data"):
    print(file)

02-14-2018.csv
02-15-2018.csv
02-16-2018.csv
02-21-2018.csv
02-22-2018.csv
02-23-2018.csv
02-28-2018.csv
03-01-2018.csv
03-02-2018.csv

In [5]:
import pandas as pd

df = pd.read_csv("../data/02-14-2018.csv")

In [6]:
print(df.shape)
df.head()

(1048575, 80)

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign

In [7]:
print(df.columns.tolist())

['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

In [9]:
print(df["Label"].value_counts())

Label
Benign            667626
FTP-BruteForce    193360
SSH-Bruteforce    187589
Name: count, dtype: int64

In [10]:
print(df.shape)
print(df.isnull().sum().sum())

(1048575, 80)
2277

In [11]:
df.isnull().sum().sort_values(ascending=False).head(20)

Flow Byts/s         2277
Dst Port               0
Timestamp              0
Protocol               0
Tot Fwd Pkts           0
Tot Bwd Pkts           0
TotLen Fwd Pkts        0
Flow Duration          0
Fwd Pkt Len Max        0
Fwd Pkt Len Min        0
Fwd Pkt Len Mean       0
Fwd Pkt Len Std        0
Bwd Pkt Len Max        0
Bwd Pkt Len Min        0
Bwd Pkt Len Mean       0
TotLen Bwd Pkts        0
Bwd Pkt Len Std        0
Flow Pkts/s            0
Flow IAT Mean          0
Flow IAT Std           0
dtype: int64

In [12]:
import numpy as np

print(np.isinf(df.select_dtypes(include=np.number)).sum().sum())

5371

In [13]:
import numpy as np

# Replace infinities with NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# Remove rows with NaN
df.dropna(inplace=True)

print(df.shape)
print(df.isnull().sum().sum())

(1044751, 80)
0

In [14]:
print(np.isinf(df.select_dtypes(include=np.number)).sum().sum())

0

In [15]:
df.dtypes.value_counts()

int64      54
float64    24
str         2
Name: count, dtype: int64

In [16]:
print(df["Label"].unique())

<StringArray>
['Benign', 'FTP-BruteForce', 'SSH-Bruteforce']
Length: 3, dtype: str

In [17]:
df["Label"] = df["Label"].apply(
    lambda x: 0 if x == "Benign" else 1
)

print(df["Label"].value_counts())

Label
0    663808
1    380943
Name: count, dtype: int64

In [18]:
df = df.drop("Timestamp", axis=1)

In [19]:
print(df.shape)
print(df["Label"].value_counts())

(1044751, 79)
Label
0    663808
1    380943
Name: count, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

X = df.drop("Label", axis=1)
y = df["Label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(835800, 78)
(208951, 78)

In [21]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [22]:
from sklearn.metrics import classification_report

pred = rf.predict(X_test)

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    132762
           1       1.00      1.00      1.00     76189

    accuracy                           1.00    208951
   macro avg       1.00      1.00      1.00    208951
weighted avg       1.00      1.00      1.00    208951

In [23]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)
print(cm)

[[132762      0]
 [     0  76189]]

In [24]:
print(X_train.shape)
print(X_test.shape)

(835800, 78)
(208951, 78)

In [25]:
import joblib

joblib.dump(rf, "../models/random_forest.pkl")

['../models/random_forest.pkl']

In [26]:
import pandas as pd

importance_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print(importance_df.head(10))

              Feature  Importance
0            Dst Port    0.139654
69   Fwd Seg Size Min    0.119404
38         Bwd Pkts/s    0.102141
66  Init Fwd Win Byts    0.091748
16        Flow Pkts/s    0.058690
37         Fwd Pkts/s    0.048282
17      Flow IAT Mean    0.041918
68  Fwd Act Data Pkts    0.039277
19       Flow IAT Max    0.037491
2       Flow Duration    0.032303

In [27]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    n_estimators=100
)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [28]:
from sklearn.metrics import classification_report

xgb_pred = xgb.predict(X_test)

print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    132762
           1       1.00      1.00      1.00     76189

    accuracy                           1.00    208951
   macro avg       1.00      1.00      1.00    208951
weighted avg       1.00      1.00      1.00    208951

In [31]:
print(importance_df.head(10))

              Feature  Importance
0            Dst Port    0.139654
69   Fwd Seg Size Min    0.119404
38         Bwd Pkts/s    0.102141
66  Init Fwd Win Byts    0.091748
16        Flow Pkts/s    0.058690
37         Fwd Pkts/s    0.048282
17      Flow IAT Mean    0.041918
68  Fwd Act Data Pkts    0.039277
19       Flow IAT Max    0.037491
2       Flow Duration    0.032303

In [33]:
xgb.fit(X_train, y_train);

print("XGBoost model trained successfully!")

XGBoost model trained successfully!

In [34]:
from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(
    random_state=42,
    n_estimators=100
)

lgbm.fit(X_train, y_train)

lgbm_pred = lgbm.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, lgbm_pred))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 304754, number of negative: 531046
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.209622 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 13834
[LightGBM] [Info] Number of data points in the train set: 835800, number of used features: 68
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.364626 -> initscore=-0.555344
[LightGBM] [Info] Start training from score -0.555344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    132762
           1       1.00      1.00      1.00     76189

    accuracy                           1.00    208951
   macro avg       1.00      1.00      1.00    208951
weighted avg       1.00      1.00      1.00    208951

In [1]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

top_features = [
    'Dst Port',
    'Fwd Seg Size Min',
    'Bwd Pkts/s',
    'Init Fwd Win Byts',
    'Flow Pkts/s',
    'Fwd Pkts/s',
    'Flow IAT Mean',
    'Fwd Act Data Pkts',
    'Flow IAT Max',
    'Flow Duration'
]

results = []

for i in range(len(top_features) + 1):
    
    features_to_remove = top_features[:i]
    
    X_train_new = X_train.drop(columns=features_to_remove)
    X_test_new = X_test.drop(columns=features_to_remove)

    model = XGBClassifier(
        random_state=42,
        enable_categorical=True
    )

    model.fit(X_train_new, y_train)

    y_pred = model.predict(X_test_new)

    acc = accuracy_score(y_test, y_pred)

    results.append({
        "Removed Features": i,
        "Accuracy": acc
    })

    print(f"Removed {i} features -> Accuracy = {acc:.6f}")

import pandas as pd

pd.DataFrame(results)

NameError: name 'X_train' is not defined

In [2]:
%whos

Variable             Type        Data/Info
------------------------------------------
XGBClassifier        type        <class 'xgboost.sklearn.XGBClassifier'>
accuracy_score       function    <function accuracy_score at 0x0000022E9B76D900>
features_to_remove   list        n=0
i                    int         0
results              list        n=0
top_features         list        n=10

In [3]:
dir()

['In',
 'Out',
 'XGBClassifier',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__vsc_ipynb_file__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'accuracy_score',
 'exit',
 'features_to_remove',
 'get_ipython',
 'i',
 'open',
 'quit',
 'results',
 'top_features']

In [4]:
%history -n

   1:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

top_features = [
    'Dst Port',
    'Fwd Seg Size Min',
    'Bwd Pkts/s',
    'Init Fwd Win Byts',
    'Flow Pkts/s',
    'Fwd Pkts/s',
    'Flow IAT Mean',
    'Fwd Act Data Pkts',
    'Flow IAT Max',
    'Flow Duration'
]

results = []

for i in range(len(top_features) + 1):

    features_to_remove = top_features[:i]

    X_train_new = X_train.drop(columns=features_to_remove)
    X_test_new = X_test.drop(columns=features_to_remove)

    model = XGBClassifier(
        random_state=42,
        enable_categorical=True
    )

    model.fit(X_train_new, y_train)

    y_pred = model.predict(X_test_new)

    acc = accuracy_score(y_test, y_pred)

    results.append({
        "Removed Features": i,
        "Accuracy": acc
    })

    print(f"Removed {i} features -> Accuracy = {acc:.6f}")

import pandas as pd

pd.DataFrame(results)
   2: %whos
   3: dir()
   4: %history -n

In [5]:
%reset_selective -f df

In [6]:
%whos DataFrame

No variables match your requested type.

In [7]:
df = pd.read_csv(...)

NameError: name 'pd' is not defined

In [8]:
import pandas as pd
import numpy as np

In [9]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

In [ ]:
import pandas as pd

df = pd.read_csv("../data/intrusion.csv")
df.head()

In [1]:
import pandas as pd

df = pd.read_csv("../data/02-14-2018.csv")

print(df.shape)
df.head()

(1048575, 80)

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign

In [ ]:
import glob

files = glob.glob("../data/*.csv")

dfs = [pd.read_csv(file) for file in files]

df = pd.concat(dfs, ignore_index=True)

In [2]:
from sklearn.model_selection import train_test_split

df = pd.read_csv("../data/02-14-2018.csv")

df = df.drop(columns=["Timestamp"])

df["Label"] = df["Label"].apply(
    lambda x: 0 if x == "Benign" else 1
)

X = df.drop(columns=["Label"])
y = df["Label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(838860, 78)
(209715, 78)

In [3]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

top_features = [
    'Dst Port',
    'Fwd Seg Size Min',
    'Bwd Pkts/s',
    'Init Fwd Win Byts',
    'Flow Pkts/s',
    'Fwd Pkts/s',
    'Flow IAT Mean',
    'Fwd Act Data Pkts',
    'Flow IAT Max',
    'Flow Duration'
]

results = []

for i in range(len(top_features) + 1):

    features_to_remove = top_features[:i]

    X_train_new = X_train.drop(columns=features_to_remove)
    X_test_new = X_test.drop(columns=features_to_remove)

    model = XGBClassifier(
        random_state=42,
        enable_categorical=True
    )

    model.fit(X_train_new, y_train)

    y_pred = model.predict(X_test_new)

    acc = accuracy_score(y_test, y_pred)

    results.append({
        "Removed Features": i,
        "Accuracy": acc
    })

    print(f"Removed {i} features -> Accuracy = {acc:.6f}")

import pandas as pd
results_df = pd.DataFrame(results)
results_df

XGBoostError: [11:10:04] C:\actions-runner\_work\xgboost\xgboost\src\data\gradient_index.h:99: Check failed: valid: Input data contains `inf` or a value too large, while `missing` is not set to `inf`

In [4]:
import numpy as np

print(np.isinf(X_train).sum().sum())
print(np.isinf(X_test).sum().sum())

4271
1100

In [5]:
import numpy as np

inf_cols = X_train.columns[np.isinf(X_train).any()]

print(inf_cols.tolist())

['Flow Byts/s', 'Flow Pkts/s']

In [6]:
import numpy as np

df.replace([np.inf, -np.inf], np.nan, inplace=True)

df.dropna(inplace=True)

In [7]:
import numpy as np

print("Train inf values:", np.isinf(X_train).sum().sum())

Train inf values: 4271

In [8]:
columns_to_drop = [
    "Timestamp",
    "Flow ID",
    "Src IP",
    "Dst IP"
]

df = df.drop(columns=columns_to_drop, errors="ignore")

In [9]:
print(df.columns.tolist())

['Dst Port', 'Protocol', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

In [10]:
X = df.drop("Label", axis=1)
y = df["Label"]

In [11]:
print([c for c in df.columns if "IP" in c or "Flow" in c or "Timestamp" in c])

['Flow Duration', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min']

In [12]:
top_features = [
    'Dst Port',
    'Fwd Seg Size Min',
    'Bwd Pkts/s',
    'Init Fwd Win Byts',
    'Flow Pkts/s',
    'Fwd Pkts/s',
    'Flow IAT Mean',
    'Fwd Act Data Pkts',
    'Flow IAT Max',
    'Flow Duration'
]

In [ ]:
import numpy as np

X_train = X_train.replace([np.inf, -np.inf], 0)
X_test = X_test.replace([np.inf, -np.inf], 0)

In [14]:
print(df["Label"].value_counts())

Label
0    663808
1    380943
Name: count, dtype: int64